[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_program = "58LCGWxNcN1dsbDaWpR4YMNxVdSA8mx7pC8z59k6nfCA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/denimcodes/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
